services:
  database:
    image: mysql:8
    container_name: mysql
    environment:
    
      - MYSQL_DATABASE=myheroesDatabase
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - database:/var/lib/mysql
    networks:
      - network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 3s
      retries: 3
  back:
    image: back
    build:
      context: java/
      dockerfile: dockerfile
    container_name: back
    depends_on:
      database:
        condition: "service_healthy"
        restart: true
    ports:
      - "8448:8448"
    environment:
      - spring.datasource.platform=mysql
      - spring.datasource.url=jdbc:mysql://mysql:3306/myheroesDatabase
      - spring.datasource.username=dbuser
      - spring.datasource.password=dbpass
    networks:
      - network
    healthcheck:
      test: ["CMD","curl","http://localhost:8448/actuator/health"]   #test api http
      interval: 10s
      timeout: 3s
      retries: 30
  front:
      image: front
      container_name: front
      build:
        context: angular/
        dockerfile: Dockerfile
      depends_on:
        back:
          condition: "service_healthy"
          restart: true
      ports:
        - "8888:80"
      environment:
        - BACKEND_URL=http://172.25.84.109:8448
volumes:
  database:

networks:
  network: