# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
defaults:
  run:
    working-directory: ./angular
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 10
      uses: actions/setup-node@v3
      with:
        node-version: 10
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: Login to scalway
      uses: docker/login-action@v3
      with:
        registry: rg.fr-par.scw.cloud/exampolytech2024
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSOWRD }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: dockerfile.gha
        push: false
        tags: rg.fr-par.scw.cloud/exampolytech2024/angular/remy:v1
